// Generated by CoffeeScript 1.6.3
var _global;

_global = this;

if (_global.HACKLEBERRY != null) {
  _global.HACKLEBERRY;
}

_global.HACKLEBERRY = {
  changeStylesheet: function(args) {
    var head, i, os, prefix, rtn, type, ua, val, _i, _len, _ref;
    ua = navigator.userAgent;
    head = document.getElementsByTagName('head')[0];
    type;
    os = '';
    if (ua.match(/AppleWebKit/)) {
      type = 'webkit';
    } else if (ua.match(/Opera/)) {
      type = 'o';
    } else if (ua.match(/Firefox/)) {
      type = 'moz';
    } else if (ua.match(/Trident/)) {
      type = 'ms';
    }
    _ref = args.file;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      val = _ref[i];
      os;
      prefix = args.pure ? '' : "" + type + "_";
      if (args.ios_android_change) {
        if (ua.indexOf('iPhone') > 0 || ua.indexOf('iPad') > 0 || ua.indexOf('iPod') > 0) {
          os = 'ios_';
        } else if (ua.indexOf('Android') > 0) {
          os = 'android_';
        }
      }
      rtn = '<link rel="stylesheet" type="text/css" href="' + args.path + prefix + os + val + '">';
      document.write(rtn);
      console.log(rtn);
    }
  }
};
